### ISSUE TITLE
Keep your code DRY

### ISSUE THREAD

**Issue by ghost** [Ricecakelove/prj-rev-bwfs-dasmoto#4]
Don't Repeat Yourself

https://github.com/Ricecakelove/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsAndCrafts/resources/css/style.css#L11

https://github.com/Ricecakelove/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsAndCrafts/resources/css/style.css#L13

See if you can avoid repeating code by putting repeated styles into a single CSS rule with multiple selectors.

For example:

```css
h1, h2, p, span {
  font-family: Helvetica;
}
```
